method: destvi
params:
  layer_ref: null
  layer_spatial: null
  use_gpu: false
  max_epochs_ref: 5
  max_epochs_spatial: 5
  plots: false
  zero_policy: zeros
  model_ref_kwargs: {}
  train_ref_kwargs: {}
  model_spatial_kwargs: {}
  train_spatial_kwargs: {}
