"""Public API for the fixed-signature ShapeMix model-version-1 core."""

from .config import ShapeMixConfig, validate_nested_ablation_configs
from .diagnostics import (
    FitDiagnostics,
    FitRecord,
    OptimizationStepRecord,
    ReconstructionAccumulator,
    ReconstructionSummary,
    RestartRecord,
)
from .likelihood import (
    ObjectiveComponents,
    chunked_objective_components_from_abundance,
    chunked_objective_components_from_raw,
    conditional_multinomial_log_prob,
    expected_bin_rates,
    expected_total_rate,
    factorized_poisson_log_likelihood,
    gamma_log_prior,
    independent_poisson_bin_log_likelihood,
    likelihood_components,
    negative_binomial_log_prob,
    objective_components_from_abundance,
    objective_components_from_raw,
    poisson_log_prob,
    positive_abundance,
)
from .map import MAPFitResult, MAPOptimizationError, fit_shapemix_map
from .signatures import (
    DEFAULT_BIN_NAMES,
    DEFAULT_LAYER_NAMES,
    DispersionDiagnostics,
    DispersionFoldAssignment,
    ReferenceSignatures,
    SignatureDiagnostics,
    assign_dispersion_folds,
    estimate_crossfit_dispersion,
    estimate_reference_signatures,
    estimate_reference_signatures_from_array,
    estimate_reference_signatures_from_layers,
    signature_parameter_sha256,
)

__all__ = [
    "DEFAULT_BIN_NAMES",
    "DEFAULT_LAYER_NAMES",
    "DispersionDiagnostics",
    "DispersionFoldAssignment",
    "FitDiagnostics",
    "FitRecord",
    "MAPFitResult",
    "MAPOptimizationError",
    "ObjectiveComponents",
    "OptimizationStepRecord",
    "ReconstructionAccumulator",
    "ReconstructionSummary",
    "ReferenceSignatures",
    "RestartRecord",
    "ShapeMixConfig",
    "SignatureDiagnostics",
    "assign_dispersion_folds",
    "chunked_objective_components_from_abundance",
    "chunked_objective_components_from_raw",
    "conditional_multinomial_log_prob",
    "estimate_crossfit_dispersion",
    "estimate_reference_signatures",
    "estimate_reference_signatures_from_array",
    "estimate_reference_signatures_from_layers",
    "expected_bin_rates",
    "expected_total_rate",
    "factorized_poisson_log_likelihood",
    "fit_shapemix_map",
    "gamma_log_prior",
    "independent_poisson_bin_log_likelihood",
    "likelihood_components",
    "negative_binomial_log_prob",
    "objective_components_from_abundance",
    "objective_components_from_raw",
    "poisson_log_prob",
    "positive_abundance",
    "signature_parameter_sha256",
    "validate_nested_ablation_configs",
]
